In [50]:
import pandas as pd
import numpy as np
# import re
import matplotlib as mtp
import seaborn as sb

In [51]:
df_ecom=pd.read_csv("D:\python work\pandas\messy_ecommerce_sales_data.csv")

In [52]:
pd.set_option("display.max_rows",1000)

In [53]:
df_ecom.head(52)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,electronic,-2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,05/01/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024

In [54]:
df_ecom.shape

(103, 11)

## *ecom dataframe column labels have whitespaces*

In [55]:
#printing each column labels to check the whitespaces in them
for i in df_ecom.columns:print(i)

ID
 Customer_Name
Order_ID
Order_Date
 Product
Category
Quantity
Price
Payment_Method
Status
Total

## *using rename() and strip() method in pandas we have removed the whitespaces*

In [56]:

for i in df_ecom.columns:
    df_ecom.rename(columns={i:i.strip()},inplace=True)
print(df_ecom.columns )

Index(['ID', 'Customer_Name', 'Order_ID', 'Order_Date', 'Product', 'Category',
       'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='object')

In [57]:
#verifying the column labels to check if the whitspaces are fixed
for i in df_ecom.columns:print(i)

ID
Customer_Name
Order_ID
Order_Date
Product
Category
Quantity
Price
Payment_Method
Status
Total

## *checking for duplicates*

In [58]:
#using duplicated function to filterout the duplcate values
df_ecom[df_ecom.duplicated(['Customer_Name'])]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,2025-07-09,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

## *Dropping the duplicated rows*

In [59]:
#deleting the duplicates using drop duplicate method
df_ecom.drop_duplicates(subset=['Customer_Name'],inplace=True)

In [60]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,electronic,-2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,05/01/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,2025-06-06,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

In [61]:
#to verify that the duplicates are dropped from our dataframe
df_ecom[df_ecom.duplicated(['Customer_Name'])]

Empty DataFrame
Columns: [ID, Customer_Name, Order_ID, Order_Date, Product, Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

## *checking for Categorical Inconsistencies*

In [62]:
df_ecom['Category'].value_counts()
# As we can see the values 'Electronics' and  'Sports' in category column has multiple incosistant duplicates with different cases

Category
Books          22
Home           20
Sports         16
Clothing       14
Electronics    10
electronic      3
ELECTRONICS     3
electronics     3
sports          1
Name: count, dtype: int64

## *replacing the inconsistant values with correct one using replace(with regex) and title method*

In [63]:
df_ecom['Category'].replace(['^e\w+','^E\w+'],'Electronics',regex=True,inplace=True)
df_ecom['Category']=df_ecom['Category'].str.title()

C:\Users\Admin\AppData\Local\Temp\ipykernel_8396\1857213889.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ecom['Category'].replace(['^e\w+','^E\w+'],'Electronics',regex=True,inplace=True)

In [64]:
# Verifying the above applied changes
df_ecom['Category'].value_counts()

Category
Books          22
Home           20
Electronics    19
Sports         17
Clothing       14
Name: count, dtype: int64

## *Checking for non numeric or negative values in numeric based column 'Quantity'*

In [65]:
df_ecom['Quantity']

0       3
1       2
2       1
3       5
4       1
5       3
6     NaN
7       5
8       1
9       5
10      5
11      2
12      4
13      1
14      2
15      2
16      4
17     -2
18      5
19      4
20      5
21      4
22      2
23      3
24      5
25      4
26      4
27      5
28      3
29      4
30      2
31      5
32      1
33      5
34     -5
35      4
36      1
37      3
38      1
39      2
40      4
41      3
42      5
43      5
44      5
45      2
46      2
47      4
48      1
49      5
50      1
51      2
52      3
53      4
54      5
55      1
56      2
57      4
58      1
59      3
60      5
61      4
62      2
63      3
64    NaN
65      2
66      2
67    NaN
68      2
69      1
70      5
71      3
72      2
73      5
74      4
75      1
76      5
77      1
78      3
79      3
80      2
81      1
82      4
83      5
84      4
85      2
86      1
87      3
88      5
89      1
90      1
91      2
92     4a
93    NaN
94      5
95      5
96    NaN
97      1
98      2
99      5
Name: Quantity, dtype: object

## *using replace() method with regex to clear the outlying values*

In [66]:
df_ecom['Quantity'].replace(regex={'[^0-9]':''},inplace=True)

In [67]:
# Verifying the column after applying the fixture.
df_ecom['Quantity']

0       3
1       2
2       1
3       5
4       1
5       3
6     NaN
7       5
8       1
9       5
10      5
11      2
12      4
13      1
14      2
15      2
16      4
17      2
18      5
19      4
20      5
21      4
22      2
23      3
24      5
25      4
26      4
27      5
28      3
29      4
30      2
31      5
32      1
33      5
34      5
35      4
36      1
37      3
38      1
39      2
40      4
41      3
42      5
43      5
44      5
45      2
46      2
47      4
48      1
49      5
50      1
51      2
52      3
53      4
54      5
55      1
56      2
57      4
58      1
59      3
60      5
61      4
62      2
63      3
64    NaN
65      2
66      2
67    NaN
68      2
69      1
70      5
71      3
72      2
73      5
74      4
75      1
76      5
77      1
78      3
79      3
80      2
81      1
82      4
83      5
84      4
85      2
86      1
87      3
88      5
89      1
90      1
91      2
92      4
93    NaN
94      5
95      5
96    NaN
97      1
98      2
99      5
Name: Quantity, dtype: object

In [68]:
# the Product value 'shoes' has inconsistent duplicate with lower case
df_ecom.groupby('Product',sort=False).count().sort_index()

,ID,Customer_Name,Order_ID,Order_Date,Category,Quantity,Price,Payment_Method,Status,Total
Product,,,,,,,,,,
Basketball,7,7,7,7,6,5,7,7,7,4
Biography,5,5,5,5,4,5,5,5,5,5
Blender,8,8,8,8,8,7,8,8,8,7
Comics,7,7,7,7,7,7,6,7,7,6
Fiction,5,5,5,5,5,5,5,5,5,5
Football,2,2,2,2,2,2,2,2,2,2
Headphones,2,2,2,2,1,2,2,2,2,2
Jacket,3,3,3,3,3,3,3,3,3,2
Jeans,3,3,3,3,2,3,2,3,3,2
Lamp,7,7,7,7,7,7,7,7,7,7
Laptop,4,4,4,4,3,4,4,4,4,4
Microwave,5,5,5,5,5,5,4,5,5,4
Science,6,6,6,6,6,6,6,6,6,6
Shoes,7,7,7,7,6,7,6,7,7,6
Smartphone,5,5,5,5,4,5,5,5,5,4
Smartwatch,3,3,3,3,3,3,3,3,3,3
T-shirt,3,3,3,3,3,3,3,3,3,3
Tennis Racket,7,7,7,7,7,6,6,7,7,5
Vacuum,5,5,5,5,4,4,5,5,5,4
Yoga Mat,5,5,5,5,5,5,5,5,5,4
shoes,1,1,1,1,1,1,1,1,1,1

In [69]:
#Ensured consistent capitalization across text fields by converting to Title Case.
df_ecom['Product']=df_ecom['Product'].str.title()

In [70]:
#Verifying to ensure the applied changes are visible in the output
df_ecom.groupby('Product',sort=False).count().sort_index()

,ID,Customer_Name,Order_ID,Order_Date,Category,Quantity,Price,Payment_Method,Status,Total
Product,,,,,,,,,,
Basketball,7,7,7,7,6,5,7,7,7,4
Biography,5,5,5,5,4,5,5,5,5,5
Blender,8,8,8,8,8,7,8,8,8,7
Comics,7,7,7,7,7,7,6,7,7,6
Fiction,5,5,5,5,5,5,5,5,5,5
Football,2,2,2,2,2,2,2,2,2,2
Headphones,2,2,2,2,1,2,2,2,2,2
Jacket,3,3,3,3,3,3,3,3,3,2
Jeans,3,3,3,3,2,3,2,3,3,2
Lamp,7,7,7,7,7,7,7,7,7,7
Laptop,4,4,4,4,3,4,4,4,4,4
Microwave,5,5,5,5,5,5,4,5,5,4
Science,6,6,6,6,6,6,6,6,6,6
Shoes,8,8,8,8,7,8,7,8,8,7
Smartphone,5,5,5,5,4,5,5,5,5,4
Smartwatch,3,3,3,3,3,3,3,3,3,3
T-Shirt,3,3,3,3,3,3,3,3,3,3
Tennis Racket,7,7,7,7,7,6,6,7,7,5
Vacuum,5,5,5,5,4,4,5,5,5,4
Yoga Mat,5,5,5,5,5,5,5,5,5,4

In [71]:
# checking for inconsistencies like unwanted characters and words in the 'Price' column values
df_ecom['Price']

0               38
1              abd
2           389.05
3           233.92
4           552.51
5           122.06
6           978.63
7           587.68
8           600.29
9           168.34
10    four hundred
11          865.77
12          752.13
13          411.81
14          413.13
15          796.84
16             NaN
17           10000
18          247.82
19          438.19
20            300$
21          523.01
22          556.93
23          615.91
24             NaN
25          765.69
26           836.8
27          336.02
28          898.69
29          736.71
30             NaN
31          616.63
32           266.7
33          343.24
34          591.53
35          446.19
36          696.71
37            -100
38          531.06
39          681.38
40          588.98
41          546.04
42          645.26
43          826.77
44          849.07
45          860.99
46          705.42
47          596.15
48          660.98
49          896.38
50          206.19
51          457.16
52          233.11
53           278.9
54          789.64
55           40.95
56             NaN
57           275.1
58          933.58
59          163.16
60          242.52
61          209.32
62          155.76
63          235.26
64          587.64
65          443.13
66          569.38
67          593.93
68          141.49
69          582.13
70          741.63
71          688.68
72          942.76
73          351.89
74          187.48
75          111.36
76          530.52
77           69.48
78          472.14
79          868.67
80          418.38
81          266.48
82          538.35
83             NaN
84          101.19
85          730.92
86          365.34
87          882.96
88          504.05
89          814.68
90          920.37
91          881.02
92          203.63
93          522.02
94          944.54
95          817.46
96             abd
97          160.16
98          497.01
99          372.28
Name: Price, dtype: object

In [72]:
#using replace(with regex) to remove the unwanted characters
df_ecom['Price'].replace(regex={'[^0-9.]':''},inplace=True)
df_ecom['Price']

0         38
1
2     389.05
3     233.92
4     552.51
5     122.06
6     978.63
7     587.68
8     600.29
9     168.34
10
11    865.77
12    752.13
13    411.81
14    413.13
15    796.84
16       NaN
17     10000
18    247.82
19    438.19
20       300
21    523.01
22    556.93
23    615.91
24       NaN
25    765.69
26     836.8
27    336.02
28    898.69
29    736.71
30       NaN
31    616.63
32     266.7
33    343.24
34    591.53
35    446.19
36    696.71
37       100
38    531.06
39    681.38
40    588.98
41    546.04
42    645.26
43    826.77
44    849.07
45    860.99
46    705.42
47    596.15
48    660.98
49    896.38
50    206.19
51    457.16
52    233.11
53     278.9
54    789.64
55     40.95
56       NaN
57     275.1
58    933.58
59    163.16
60    242.52
61    209.32
62    155.76
63    235.26
64    587.64
65    443.13
66    569.38
67    593.93
68    141.49
69    582.13
70    741.63
71    688.68
72    942.76
73    351.89
74    187.48
75    111.36
76    530.52
77     69.48
78    472.14
79    868.67
80    418.38
81    266.48
82    538.35
83       NaN
84    101.19
85    730.92
86    365.34
87    882.96
88    504.05
89    814.68
90    920.37
91    881.02
92    203.63
93    522.02
94    944.54
95    817.46
96
97    160.16
98    497.01
99    372.28
Name: Price, dtype: object

In [73]:
# checking for inconsistencies like inconsistant date formats and random wordings in the 'Order_Date' column values
df_ecom['Order_Date']

0     2024-11-22
1     2025-07-05
2     2024-12-23
3     2025-03-19
4     2025-10-20
5     2024-11-20
6     2025-02-02
7     2025-01-03
8     2025-10-23
9     2025-05-03
10    2025-09-26
11    2025-10-22
12    2025-03-02
13    2025-07-24
14    Jan 5 2023
15    2025-01-10
16    2025-10-30
17    2025-02-12
18    2025-05-31
19    2024-12-19
20    2025-06-13
21    2025-10-11
22    2025-05-16
23    2025-10-06
24    2025-05-31
25    2025-02-09
26    2025-05-18
27    2025-05-12
28    2024-11-10
29    2025-06-22
30    2025-08-15
31    2025-06-11
32    2025-04-02
33    2024-12-05
34    2025-10-04
35    2025-02-09
36    2025-06-12
37    2025-02-23
38    2025-08-09
39    2025-02-09
40    2025-02-26
41    2025-02-13
42    2025-10-30
43    2025-07-11
44    2025-01-27
45    05/01/2023
46    2025-07-09
47    2025-05-01
48    2025-03-13
49    2025-06-29
50    2024-11-27
51    2025-07-01
52    2025-09-22
53    2025-07-16
54    2025-02-21
55    2025-05-01
56    2024-11-28
57    2025-11-06
58    2025-04-05
59    2025-07-28
60    2025-01-03
61    2024-12-15
62    2025-05-19
63    2023-01-05
64    2025-02-09
65    2024-11-08
66    2025-07-03
67    2025-08-07
68    2025-11-04
69    2025-08-12
70    2025-10-03
71    2024-12-06
72    2024-11-18
73    2025-10-11
74    2025-09-20
75    2025-02-24
76    2025-07-22
77    2025-07-28
78    2025-09-18
79    2025-09-03
80    2025-03-26
81    2024-12-29
82    2025-08-03
83    2025-03-10
84    2025-02-15
85    2025-08-14
86    2025-10-06
87    2024-11-19
88    2024-11-19
89    2025-08-14
90    2025-06-29
91    2025-07-18
92           abc
93    2025-06-06
94    2025-02-10
95    2025-06-19
96    2024-12-23
97    2025-06-23
98    2025-07-27
99    2025-01-22
Name: Order_Date, dtype: object

In [74]:
#using replace(with regex) to remove the random wordings
df_ecom['Order_Date'].replace(regex={'([a-zA-Z]+)$':''},inplace=True)
df_ecom['Order_Date']

0     2024-11-22
1     2025-07-05
2     2024-12-23
3     2025-03-19
4     2025-10-20
5     2024-11-20
6     2025-02-02
7     2025-01-03
8     2025-10-23
9     2025-05-03
10    2025-09-26
11    2025-10-22
12    2025-03-02
13    2025-07-24
14    Jan 5 2023
15    2025-01-10
16    2025-10-30
17    2025-02-12
18    2025-05-31
19    2024-12-19
20    2025-06-13
21    2025-10-11
22    2025-05-16
23    2025-10-06
24    2025-05-31
25    2025-02-09
26    2025-05-18
27    2025-05-12
28    2024-11-10
29    2025-06-22
30    2025-08-15
31    2025-06-11
32    2025-04-02
33    2024-12-05
34    2025-10-04
35    2025-02-09
36    2025-06-12
37    2025-02-23
38    2025-08-09
39    2025-02-09
40    2025-02-26
41    2025-02-13
42    2025-10-30
43    2025-07-11
44    2025-01-27
45    05/01/2023
46    2025-07-09
47    2025-05-01
48    2025-03-13
49    2025-06-29
50    2024-11-27
51    2025-07-01
52    2025-09-22
53    2025-07-16
54    2025-02-21
55    2025-05-01
56    2024-11-28
57    2025-11-06
58    2025-04-05
59    2025-07-28
60    2025-01-03
61    2024-12-15
62    2025-05-19
63    2023-01-05
64    2025-02-09
65    2024-11-08
66    2025-07-03
67    2025-08-07
68    2025-11-04
69    2025-08-12
70    2025-10-03
71    2024-12-06
72    2024-11-18
73    2025-10-11
74    2025-09-20
75    2025-02-24
76    2025-07-22
77    2025-07-28
78    2025-09-18
79    2025-09-03
80    2025-03-26
81    2024-12-29
82    2025-08-03
83    2025-03-10
84    2025-02-15
85    2025-08-14
86    2025-10-06
87    2024-11-19
88    2024-11-19
89    2025-08-14
90    2025-06-29
91    2025-07-18
92
93    2025-06-06
94    2025-02-10
95    2025-06-19
96    2024-12-23
97    2025-06-23
98    2025-07-27
99    2025-01-22
Name: Order_Date, dtype: object

In [119]:
# Alternate way to replace the inconsistent date formats which doesn't follow the basic 'yyyy-mm=dd' format
# import re
# for i,v in df_ecom['Order_Date'].items():
     # if not re.search('^([0-9]+-[0-9]+-[0-9]+)',v):
        # df_ecom.loc[i,'Order_Date']=str(pd.to_datetime(v))[:10]

#### *Breakdown of how inconsistant date formats are converted into timestamps and how we extract 'yyyy-mm=dd' format from it using to_datetime method and string slicing*

In [255]:
# it takes any type of value which is valid and returns a timstamp of the same.
pd.to_datetime('2024-12-29')

Timestamp('2024-12-29 00:00:00')

In [254]:
# Timestamp type data needs to be converted to string type in order to slice it
str(pd.to_datetime('2024-12-29'))[:10]

'2024-12-29'

In [75]:
# Using to_datetime() method along with apply + lambda function to replace the inconsistent date formats 
# which doesn't follow the basic 'yyyy-mm=dd' format
df_ecom['Order_Date']=df_ecom['Order_Date'].apply(lambda x:str(pd.to_datetime(x))[:10])

In [76]:
# verifying the output based on the above changes 
# all the inconsistencies in the date format is fixed
df_ecom['Order_Date']

0     2024-11-22
1     2025-07-05
2     2024-12-23
3     2025-03-19
4     2025-10-20
5     2024-11-20
6     2025-02-02
7     2025-01-03
8     2025-10-23
9     2025-05-03
10    2025-09-26
11    2025-10-22
12    2025-03-02
13    2025-07-24
14    2023-01-05
15    2025-01-10
16    2025-10-30
17    2025-02-12
18    2025-05-31
19    2024-12-19
20    2025-06-13
21    2025-10-11
22    2025-05-16
23    2025-10-06
24    2025-05-31
25    2025-02-09
26    2025-05-18
27    2025-05-12
28    2024-11-10
29    2025-06-22
30    2025-08-15
31    2025-06-11
32    2025-04-02
33    2024-12-05
34    2025-10-04
35    2025-02-09
36    2025-06-12
37    2025-02-23
38    2025-08-09
39    2025-02-09
40    2025-02-26
41    2025-02-13
42    2025-10-30
43    2025-07-11
44    2025-01-27
45    2023-05-01
46    2025-07-09
47    2025-05-01
48    2025-03-13
49    2025-06-29
50    2024-11-27
51    2025-07-01
52    2025-09-22
53    2025-07-16
54    2025-02-21
55    2025-05-01
56    2024-11-28
57    2025-11-06
58    2025-04-05
59    2025-07-28
60    2025-01-03
61    2024-12-15
62    2025-05-19
63    2023-01-05
64    2025-02-09
65    2024-11-08
66    2025-07-03
67    2025-08-07
68    2025-11-04
69    2025-08-12
70    2025-10-03
71    2024-12-06
72    2024-11-18
73    2025-10-11
74    2025-09-20
75    2025-02-24
76    2025-07-22
77    2025-07-28
78    2025-09-18
79    2025-09-03
80    2025-03-26
81    2024-12-29
82    2025-08-03
83    2025-03-10
84    2025-02-15
85    2025-08-14
86    2025-10-06
87    2024-11-19
88    2024-11-19
89    2025-08-14
90    2025-06-29
91    2025-07-18
92           NaT
93    2025-06-06
94    2025-02-10
95    2025-06-19
96    2024-12-23
97    2025-06-23
98    2025-07-27
99    2025-01-22
Name: Order_Date, dtype: object

## *checking for null values in the dataframe using isna() method*

In [77]:
df_ecom.isna().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [78]:
df_ecom[df_ecom['Category'].isna()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.20
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.71
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.76
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.48
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.40
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.76
93,193,Customer_193,ORD-42475,2025-06-06,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.02

In [79]:
# finding the row with most Null values and which can be dropped
df_ecom[df_ecom[['Category','Quantity','Total']].isna().all(axis=1)]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
93,193,Customer_193,ORD-42475,2025-06-06,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN

In [81]:
# using inverse operator along with above condition , we can remove the null row
df_ecom=df_ecom[~df_ecom[['Category','Quantity','Total']].isna().all(axis=1)]

In [82]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,NaN,,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

## *Dealing with null values using mode() method*

In [83]:
#mode() method helps fining the most appearing or popular value
df_ecom['Quantity'].mode()

0    5
Name: Quantity, dtype: object

In [84]:
#it returns a Sereis type output which is indexable
type(df_ecom['Quantity'].mode())

pandas.core.series.Series

In [85]:
# the mode() output is extracted and stored in a variable for later use
mode_value=df_ecom['Quantity'].mode()[0]
mode_value

'5'

In [86]:
#filling up all the null values in ouantity column with the mode() output value
df_ecom.fillna({'Quantity':mode_value},inplace=True)

In [87]:
# verfying if the applied changes have taken effect . As we can see the Quantity column has 0 null value          
df_ecom.isna().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           7
Quantity           0
Price              5
Payment_Method     0
Status             0
Total             13
dtype: int64

# *filling all the null values using backward or forward fill method "bfill() or ffill()"*

In [38]:
# we are going to fill the null in the catagory based on the respective product
#sorting the values based on product
df_ecom.sort_values('Product',inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_8396\93190001.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ecom.sort_values('Product',inplace=True)

In [39]:
# finding the indexes of null valued rows
df_ecom[df_ecom['Category'].isna()].index

Index([33, 36, 84, 80, 82, 81, 98], dtype='int64')

In [40]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010

### *creating seperate dataframes for ffill and bfill*

In [41]:
# ffill=33,84,80,82,81,23
ff=df_ecom['Category'].ffill()
ff

21         Sports
69         Sports
67         Sports
19         Sports
10         Sports
46    Electronics
95          Books
4           Books
68          Books
7           Books
33          Books
0            Home
27           Home
62           Home
97           Home
54           Home
17    Electronics
99           Home
6            Home
49          Books
11          Books
72          Books
51          Books
25          Books
76          Books
24          Books
91          Books
40          Books
41          Books
15          Books
13          Books
85         Sports
44         Sports
36         Sports
75    Electronics
92       Clothing
57       Clothing
47       Clothing
70       Clothing
56       Clothing
84       Clothing
52           Home
73           Home
38           Home
31           Home
28    Electronics
89           Home
94           Home
45    Electronics
77    Electronics
80    Electronics
86    Electronics
16           Home
88           Home
22           Home
74    Electronics
59           Home
3           Books
8           Books
61          Books
18          Books
29          Books
60          Books
55       Clothing
26       Clothing
65       Clothing
12       Clothing
83       Clothing
82       Clothing
71       Clothing
42       Clothing
1     Electronics
14    Electronics
87    Electronics
81    Electronics
39    Electronics
35    Electronics
58    Electronics
63    Electronics
66    Electronics
43       Clothing
34       Clothing
9          Sports
2          Sports
64         Sports
30         Sports
78         Sports
5          Sports
48         Sports
37           Home
90           Home
23    Electronics
98    Electronics
96           Home
53         Sports
50         Sports
20    Electronics
32    Electronics
79         Sports
Name: Category, dtype: object

In [42]:
# bfill=36
bf=df_ecom['Category'].bfill()
bf

21         Sports
69         Sports
67         Sports
19         Sports
10         Sports
46    Electronics
95          Books
4           Books
68          Books
7           Books
33           Home
0            Home
27           Home
62           Home
97           Home
54           Home
17    Electronics
99           Home
6            Home
49          Books
11          Books
72          Books
51          Books
25          Books
76          Books
24          Books
91          Books
40          Books
41          Books
15          Books
13          Books
85         Sports
44         Sports
36    Electronics
75    Electronics
92       Clothing
57       Clothing
47       Clothing
70       Clothing
56       Clothing
84           Home
52           Home
73           Home
38           Home
31           Home
28    Electronics
89           Home
94           Home
45    Electronics
77    Electronics
80    Electronics
86    Electronics
16           Home
88           Home
22           Home
74    Electronics
59           Home
3           Books
8           Books
61          Books
18          Books
29          Books
60          Books
55       Clothing
26       Clothing
65       Clothing
12       Clothing
83       Clothing
82       Clothing
71       Clothing
42       Clothing
1     Electronics
14    Electronics
87    Electronics
81    Electronics
39    Electronics
35    Electronics
58    Electronics
63    Electronics
66    Electronics
43       Clothing
34       Clothing
9          Sports
2          Sports
64         Sports
30         Sports
78         Sports
5          Sports
48         Sports
37           Home
90           Home
23    Electronics
98           Home
96           Home
53         Sports
50         Sports
20    Electronics
32    Electronics
79         Sports
Name: Category, dtype: object

### *now locating the null values and replacing with the respective backward /forward fill dataframes*

In [43]:
df_ecom.loc[36,'Category']=bf.loc[36]

In [44]:
df_ecom.loc[[33,84,80,82,81,23],'Category']=ff.loc[[33,84,80,82,81,23]]

In [45]:
df_ecom.loc[98,'Category']=ff.loc[98]

In [46]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
33,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5,343.24,Credit Card,Shipped,1716.200
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,Electronics,1,696.71,Credit Card,Delivered,696.710
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,Clothing,4,101.19,Bank Transfer,Processing,404.760
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,Electronics,2,418.38,Credit Card,Processing,836.760
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,Clothing,4,538.35,PayPal,Processing,2153.400
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Electronics,1,266.48,Cash on Delivery,Cancelled,266.480
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Electronics,2,497.01,Cash on Delivery,Shipped,994.020
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010

In [47]:
df_ecom.sort_values('ID',inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_8396\4174536630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ecom.sort_values('ID',inplace=True)

In [48]:
# verifying the applied changes
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,Electronics,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,Electronics,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Electronics,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,Clothing,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,Clothing,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Electronics,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

# *Alternate way of dealing null values by automating the forward and backward filling process*

In [91]:
# making a copy of the main dataframe
df3=df_ecom.copy()
df3

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

In [90]:
#sorting the values based on product
df3=df3.sort_values('Product',ignore_index=True)
df3

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
1,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
2,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
3,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
4,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
5,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
6,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
7,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
8,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
9,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
10,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
11,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
12,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
13,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
14,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
15,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
16,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
17,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
18,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
19,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
20,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
21,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
22,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
23,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
24,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
25,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
26,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
27,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
28,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
29,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
30,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
31,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
32,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
33,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
34,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
35,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
36,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
37,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
38,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
39,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
40,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
41,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
42,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
43,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
44,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
45,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
46,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
47,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
48,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
49,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
50,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
51,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
52,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
53,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
54,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
55,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
56,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
57,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
58,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
59,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
60,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
61,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
62,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
63,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
64,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
67,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
68,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
69,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
70,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
71,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
72,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
73,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
74,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
75,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
76,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
77,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
78,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
79,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
80,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
81,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
82,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
83,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
84,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
85,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
86,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
87,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
88,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
89,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
92,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
93,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
94,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
95,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
96,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
97,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
98,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010

In [289]:
# automating the filling process uaing for loop and if statement.this would fill forward value or backward value based on the conditions given, thus filling up all the null values in one go.
for i in df3.index:
    if type(df3.loc[i,'Category'])==str:
        continue
    elif df3.loc[i,'Product']==df3.loc[i+1,'Product']:
        df3.loc[i,'Category']=df3.loc[i+1,'Category']
    elif  (i!=0) & (df3.loc[i,'Product']==df3.loc[i-1,'Product']):
        df3.loc[i,'Category']=df3.loc[i-1,'Category']
     
df3

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
1,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
2,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
3,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
4,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
5,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
6,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
7,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
8,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
9,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
10,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5,343.24,Credit Card,Shipped,1716.200
11,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
12,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
13,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
14,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
15,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
16,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
17,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
18,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
19,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
20,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
21,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
22,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
23,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
24,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
25,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
26,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
27,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
28,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
29,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
30,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
31,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
32,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
33,136,Customer_136,ORD-20985,2025-06-12,Headphones,Electronics,1,696.71,Credit Card,Delivered,696.710
34,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
35,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
36,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
37,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
38,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
39,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
40,184,Customer_184,ORD-67799,2025-02-15,Jeans,Clothing,4,101.19,Bank Transfer,Processing,404.760
41,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
42,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
43,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
44,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
45,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
46,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
47,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
48,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
49,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
50,180,Customer_180,ORD-86629,2025-03-26,Laptop,Electronics,2,418.38,Credit Card,Processing,836.760
51,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
52,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
53,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
54,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
55,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
56,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
57,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
58,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
59,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
60,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
61,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
62,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
63,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
64,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
67,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
68,182,Customer_182,ORD-79672,2025-08-03,Shoes,Clothing,4,538.35,PayPal,Processing,2153.400
69,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
70,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
71,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
72,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
73,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
74,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Electronics,1,266.48,Cash on Delivery,Cancelled,266.480
75,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
76,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
77,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
78,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
79,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
80,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
81,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
82,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
83,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
84,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
85,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
86,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
87,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
88,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
89,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
92,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Home,2,497.01,Cash on Delivery,Shipped,994.020
93,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
94,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
95,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
96,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
97,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
98,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010

In [290]:
# reverting back to the original sort order of the dataframe
df3=df3.sort_values('ID',ignore_index=True)
df3

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,Electronics,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,Electronics,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Electronics,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,Clothing,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,Clothing,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
93,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
94,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
95,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,,PayPal,Delivered,NaN
96,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
97,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Home,2,497.01,Cash on Delivery,Shipped,994.020
98,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

In [291]:
#crosschecking the null values after applying the above changes
df3.isna().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           0
Quantity           0
Price              5
Payment_Method     0
Status             0
Total             13
dtype: int64

### *dealing with nulls in Price column using median() and fillna() method*

In [92]:
# making a copy of the main dataframe 
dfcpy=df3.copy()

In [93]:
#removing the empltyspaces
dfcpy['Price']=dfcpy['Price'].dropna().replace('',np.nan)

In [94]:
#dropping all the null values in order to calculate the median of the price column
md_value=dfcpy['Price'].dropna().astype('float64').median()
md_value

538.35

In [ ]:
#updating the main file with the copied version
df3['Price']=dfcpy['Price']

In [96]:
df3

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,NaN,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

In [97]:
# filling up the null values with the median output
df3['Price']=df3['Price'].fillna(md_value)

In [98]:
#updating the main ecom dataframe and verifying the changes
df_ecom=df3
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,538.35,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,538.35,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,538.35,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,538.35,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,538.35,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,538.35,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

In [299]:

df_ecom.isna().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           0
Quantity           0
Price              0
Payment_Method     0
Status             0
Total             13
dtype: int64

In [300]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,538.35,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,538.35,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,538.35,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,Books,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,Electronics,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,538.35,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,Electronics,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,Electronics,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,Clothing,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,538.35,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,Clothing,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
93,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
94,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
95,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,538.35,PayPal,Delivered,NaN
96,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
97,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Home,2,497.01,Cash on Delivery,Shipped,994.020
98,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

### *finding 'NaT' in Order_Date column replacing with a random sampled value using sample()*

In [99]:
#finding a random sample value from the dataframe(excluding the NaT values)
df_ecom.query("Order_Date!='NaT'").sample(1)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.58

In [ ]:
#extracting the sample date inorder to replace the NaT values

In [100]:
for i in df_ecom.query("Order_Date!='NaT'").sample(1)['Order_Date']:
    rand_date=i

In [101]:
rand_date

'2025-08-09'

In [102]:
# condition to find NaT values and replace the same with sample date and verifying the changes
for i in df_ecom['Order_Date'].index:
    if df_ecom.loc[i,'Order_Date']=='NaT':
        df_ecom.loc[i,'Order_Date']=rand_date
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,538.35,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000,Cash on Delivery,Processing,-200000.000
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,538.35,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,538.35,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,538.35,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,538.35,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,2025-08-09,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,538.35,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400

# *Converting the 'Quantity', 'Price' columns into numeric type to calculate revenue and deleting the 'Total' column*

In [103]:
#changing the data type of the numeric columns accordingly
df_ecom=df_ecom.astype({'Quantity':'int64','Price':'float'})

In [104]:
#verifying the dtypes after the changes applied
df_ecom.dtypes

ID                  int64
Customer_Name      object
Order_ID           object
Order_Date         object
Product            object
Category           object
Quantity            int64
Price             float64
Payment_Method     object
Status             object
Total             float64
dtype: object

In [105]:
#Calculating the revenue and assigning it to as a new column
# revenue=qantity of the product * its price
df_ecom['Revenue']=df_ecom['Quantity'] * df_ecom['Price']

In [106]:
#comparing the 'Revenue' column to 'Total' column
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total,Revenue
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38.00,Cash on Delivery,Shipped,114.000,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,NaN,1076.70
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510,552.51
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180,366.18
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,NaN,4893.15
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.400,2938.40
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.290,600.29
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700,841.70
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,NaN,2691.75
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.540,1731.54
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520,3008.52
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.810,411.81
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260,826.26
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576,1593.68
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,538.35,Cash on Delivery,Processing,NaN,2153.40
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000.00,Cash on Delivery,Processing,-200000.000,20000.00
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.100,1239.10
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760,1752.76
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300.00,Credit Card,Cancelled,NaN,1500.00
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040,2092.04
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.860,1113.86
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.730,1847.73
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,538.35,PayPal,Cancelled,NaN,2691.75
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.760,3062.76
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.80,Bank Transfer,Cancelled,3347.200,3347.20
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100,1680.10
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.070,2696.07
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.840,2946.84
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,538.35,Bank Transfer,Processing,NaN,1076.70
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.150,3083.15
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.70,PayPal,Delivered,266.700,266.70
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200,1716.20
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,-2957.650,2957.65
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.760,1784.76
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710,696.71
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100.00,Cash on Delivery,Delivered,-300.000,300.00
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.060,531.06
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760,1362.76
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.920,2355.92
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120,1638.12
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410,3226.30
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850,4133.85
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350,4245.35
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980,1721.98
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.840,1410.84
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600,2384.60
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980,660.98
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900,4481.90
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190,206.19
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,640.024,914.32
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.330,699.33
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.90,Cash on Delivery,Processing,1115.600,1115.60
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200,3948.20
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.950,40.95
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,538.35,Bank Transfer,Shipped,NaN,1076.70
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.10,Bank Transfer,Processing,1100.400,1100.40
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580,933.58
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.480,489.48
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600,1212.60
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.280,837.28
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.520,311.52
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780,705.78
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,NaN,2938.20
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260,886.26
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.760,1138.76
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,NaN,2969.65
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.980,282.98
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.130,582.13
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150,3708.15
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040,2066.04
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520,1885.52
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450,1759.45
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.920,749.92
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360,111.36
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600,2652.60
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480,69.48
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420,1416.42
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010,2606.01
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.760,836.76
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480,266.48
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.400,2153.40
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,538.35,Cash on Delivery,Returned,NaN,2691.75
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760,404.76
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288,1461.84
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340,365.34
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880,2648.88
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250,2520.25
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680,814.68
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370,920.37
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040,1762.04
92,192,Customer_192,ORD-35144,2025-08-09,Jacket,Clothing,4,203.63,Credit Card,Returned,NaN,814.52
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700,4722.70
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300,4087.30
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,538.35,PayPal,Delivered,NaN,2691.75
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160,160.16
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020,994.02
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400,1861.40

### *deleting 'Total' column using drop() method*

In [107]:
# dropping the messy 'Total' column for a clean 'Revenue' column which possess the same data.
df_ecom.drop(columns='Total',inplace=True)

In [108]:
df_ecom

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Revenue
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,1076.70
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.18
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Home,5,978.63,Bank Transfer,Processing,4893.15
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.40
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.29
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.70
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,2691.75
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.54
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.52
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.81
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.26
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1593.68
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Home,4,538.35,Cash on Delivery,Processing,2153.40
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000.00,Cash on Delivery,Processing,20000.00
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.10
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.76
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Electronics,5,300.00,Credit Card,Cancelled,1500.00
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.04
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Home,2,556.93,PayPal,Shipped,1113.86
23,123,Customer_123,ORD-11314,2025-10-06,Vacuum,Electronics,3,615.91,Cash on Delivery,Cancelled,1847.73
24,124,Customer_124,ORD-46136,2025-05-31,Comics,Books,5,538.35,PayPal,Cancelled,2691.75
25,125,Customer_125,ORD-23202,2025-02-09,Comics,Books,4,765.69,PayPal,Shipped,3062.76
26,126,Customer_126,ORD-11261,2025-05-18,Shoes,Clothing,4,836.80,Bank Transfer,Cancelled,3347.20
27,127,Customer_127,ORD-65482,2025-05-12,Blender,Home,5,336.02,Bank Transfer,Returned,1680.10
28,128,Customer_128,ORD-12270,2024-11-10,Lamp,Electronics,3,898.69,Bank Transfer,Delivered,2696.07
29,129,Customer_129,ORD-48863,2025-06-22,Science,Books,4,736.71,Bank Transfer,Returned,2946.84
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,Sports,2,538.35,Bank Transfer,Processing,1076.70
31,131,Customer_131,ORD-91396,2025-06-11,Lamp,Home,5,616.63,PayPal,Shipped,3083.15
32,132,Customer_132,ORD-40186,2025-04-02,Yoga Mat,Electronics,1,266.70,PayPal,Delivered,266.70
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5,343.24,Credit Card,Shipped,1716.20
34,134,Customer_134,ORD-16585,2025-10-04,T-Shirt,Clothing,5,591.53,PayPal,Shipped,2957.65
35,135,Customer_135,ORD-33656,2025-02-09,Smartwatch,Electronics,4,446.19,Cash on Delivery,Cancelled,1784.76
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1,696.71,Credit Card,Delivered,696.71
37,137,Customer_137,ORD-91254,2025-02-23,Vacuum,Home,3,100.00,Cash on Delivery,Delivered,300.00
38,138,Customer_138,ORD-34319,2025-08-09,Lamp,Home,1,531.06,PayPal,Processing,531.06
39,139,Customer_139,ORD-38418,2025-02-09,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.76
40,140,Customer_140,ORD-67096,2025-02-26,Fiction,Books,4,588.98,Credit Card,Returned,2355.92
41,141,Customer_141,ORD-45059,2025-02-13,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.12
42,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.30
43,143,Customer_143,ORD-14329,2025-07-11,T-Shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.85
44,144,Customer_144,ORD-89452,2025-01-27,Football,Sports,5,849.07,Bank Transfer,Processing,4245.35
45,145,Customer_145,ORD-75314,2023-05-01,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.98
46,146,Customer_146,ORD-32755,2025-07-09,Basketball,Electronics,2,705.42,Bank Transfer,Processing,1410.84
47,147,Customer_147,ORD-80707,2025-05-01,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.60
48,148,Customer_148,ORD-38423,2025-03-13,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.98
49,149,Customer_149,ORD-95911,2025-06-29,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.90
50,150,Customer_150,ORD-76902,2024-11-27,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.19
51,151,Customer_151,ORD-56552,2025-07-01,Comics,Books,2,457.16,PayPal,Processing,914.32
52,152,Customer_152,ORD-72869,2025-09-22,Lamp,Home,3,233.11,PayPal,Returned,699.33
53,153,Customer_153,ORD-29721,2025-07-16,Yoga Mat,Sports,4,278.90,Cash on Delivery,Processing,1115.60
54,154,Customer_154,ORD-95990,2025-02-21,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.20
55,155,Customer_155,ORD-20182,2025-05-01,Shoes,Clothing,1,40.95,PayPal,Returned,40.95
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,Clothing,2,538.35,Bank Transfer,Shipped,1076.70
57,157,Customer_157,ORD-34407,2025-11-06,Jacket,Clothing,4,275.10,Bank Transfer,Processing,1100.40
58,158,Customer_158,ORD-35817,2025-04-05,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.58
59,159,Customer_159,ORD-98162,2025-07-28,Microwave,Home,3,163.16,PayPal,Shipped,489.48
60,160,Customer_160,ORD-96037,2025-01-03,Science,Books,5,242.52,Cash on Delivery,Returned,1212.60
61,161,Customer_161,ORD-27653,2024-12-15,Science,Books,4,209.32,Bank Transfer,Shipped,837.28
62,162,Customer_162,ORD-27743,2025-05-19,Blender,Home,2,155.76,Credit Card,Returned,311.52
63,163,Customer_163,ORD-24378,2023-01-05,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.78
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,Sports,5,587.64,Credit Card,Returned,2938.20
65,165,Customer_165,ORD-55695,2024-11-08,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.26
66,166,Customer_166,ORD-97756,2025-07-03,T-Shirt,Electronics,2,569.38,Cash on Delivery,Shipped,1138.76
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,Sports,5,593.93,Cash on Delivery,Processing,2969.65
68,168,Customer_168,ORD-53430,2025-11-04,Biography,Books,2,141.49,PayPal,Cancelled,282.98
69,169,Customer_169,ORD-75539,2025-08-12,Basketball,Sports,1,582.13,Credit Card,Returned,582.13
70,170,Customer_170,ORD-21530,2025-10-03,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.15
71,171,Customer_171,ORD-99790,2024-12-06,Shoes,Clothing,3,688.68,PayPal,Processing,2066.04
72,172,Customer_172,ORD-48008,2024-11-18,Comics,Books,2,942.76,Bank Transfer,Returned,1885.52
73,173,Customer_173,ORD-42171,2025-10-11,Lamp,Home,5,351.89,Credit Card,Shipped,1759.45
74,174,Customer_174,ORD-16766,2025-09-20,Microwave,Electronics,4,187.48,Credit Card,Returned,749.92
75,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,111.36
76,176,Customer_176,ORD-95794,2025-07-22,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.60
77,177,Customer_177,ORD-64136,2025-07-28,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.48
78,178,Customer_178,ORD-89906,2025-09-18,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.42
79,179,Customer_179,ORD-99328,2025-09-03,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.01
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2,418.38,Credit Card,Processing,836.76
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.48
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4,538.35,PayPal,Processing,2153.40
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,Clothing,5,538.35,Cash on Delivery,Returned,2691.75
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.76
85,185,Customer_185,ORD-57123,2025-08-14,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1461.84
86,186,Customer_186,ORD-90569,2025-10-06,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.34
87,187,Customer_187,ORD-41292,2024-11-19,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.88
88,188,Customer_188,ORD-58590,2024-11-19,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.25
89,189,Customer_189,ORD-30627,2025-08-14,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.68
90,190,Customer_190,ORD-38469,2025-06-29,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.37
91,191,Customer_191,ORD-41810,2025-07-18,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.04
92,192,Customer_192,ORD-35144,2025-08-09,Jacket,Clothing,4,203.63,Credit Card,Returned,814.52
94,194,Customer_194,ORD-69764,2025-02-10,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.70
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,5,538.35,PayPal,Delivered,2691.75
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.40

### *Dealing with mismatched data in 'Category' column with respective 'Product' data*

In [337]:
# some of Product data are not matching with the Catagory labels as bellow few examples
df_ecom.loc[[46,32],['Category','Product']]

       Category     Product
46  Electronics  Basketball
32  Electronics    Yoga Mat

In [109]:
# creating a copy to work on
dfcpy=df_ecom.copy()

In [404]:
dfcpy['Category'].unique()

array(['Electronics', 'Sports', 'Books', 'Clothing', 'Home'], dtype=object)

In [403]:
# distinct products in 'Product' column
dfcpy['Product'].unique()

array(['Blender', 'Smartphone', 'Tennis Racket', 'Science', 'Biography',
       'Basketball', 'Comics', 'Shoes', 'Fiction', 'Microwave',
       'Yoga Mat', 'Vacuum', 'Lamp', 'T-Shirt', 'Smartwatch',
       'Headphones', 'Football', 'Laptop', 'Jacket', 'Jeans'],
      dtype=object)

### *automating the process to fill in with correct catagory name with respective to the product name*

In [396]:
for i,v in dfcpy['Product'].items():
    if v in {'Science','Biography','Comics','Fiction'}:
        dfcpy.loc[i,'Category']='Books'
    elif  v in {'Shoes','Jeans','Jacket','T-Shirt'}:
        dfcpy.loc[i,'Category']='Clothing'
    elif v in {'Blender', 'Smartphone','Vacuum','Headphones','Laptop','Microwave','Smartwatch'}:
        dfcpy.loc[i,'Category']='Electronics'
    elif v in {'Tennis Racket','Basketball','Yoga Mat', 'Football'}:
        dfcpy.loc[i,'Category']='Sports'
    else:dfcpy.loc[i,'Category']='Home'

In [408]:
dfcpy.loc[:,['Product','Category']].sort_values('Category')

          Product     Category
49         Comics        Books
29        Science        Books
76         Comics        Books
25         Comics        Books
24         Comics        Books
68      Biography        Books
40        Fiction        Books
18        Science        Books
41        Fiction        Books
33      Biography        Books
13        Fiction        Books
61        Science        Books
15        Fiction        Books
94      Biography        Books
51         Comics        Books
3         Science        Books
4       Biography        Books
11         Comics        Books
60        Science        Books
72         Comics        Books
8         Science        Books
91        Fiction        Books
7       Biography        Books
65          Shoes     Clothing
66        T-Shirt     Clothing
70          Jeans     Clothing
42          Shoes     Clothing
71          Shoes     Clothing
34        T-Shirt     Clothing
43        T-Shirt     Clothing
57         Jacket     Clothing
47         Jacket     Clothing
55          Shoes     Clothing
56          Jeans     Clothing
26          Shoes     Clothing
82          Shoes     Clothing
83          Shoes     Clothing
84          Jeans     Clothing
92         Jacket     Clothing
12          Shoes     Clothing
75     Headphones  Electronics
96        Blender  Electronics
95         Vacuum  Electronics
58     Smartwatch  Electronics
59      Microwave  Electronics
90         Vacuum  Electronics
88      Microwave  Electronics
63     Smartwatch  Electronics
74      Microwave  Electronics
87     Smartphone  Electronics
86         Laptop  Electronics
81     Smartphone  Electronics
80         Laptop  Electronics
62        Blender  Electronics
77         Laptop  Electronics
0         Blender  Electronics
27        Blender  Electronics
1      Smartphone  Electronics
6         Blender  Electronics
14     Smartphone  Electronics
16      Microwave  Electronics
17        Blender  Electronics
22      Microwave  Electronics
23         Vacuum  Electronics
54        Blender  Electronics
35     Smartwatch  Electronics
36     Headphones  Electronics
37         Vacuum  Electronics
98        Blender  Electronics
39     Smartphone  Electronics
97         Vacuum  Electronics
45         Laptop  Electronics
38           Lamp         Home
52           Lamp         Home
73           Lamp         Home
31           Lamp         Home
89           Lamp         Home
28           Lamp         Home
93           Lamp         Home
69     Basketball       Sports
10     Basketball       Sports
5   Tennis Racket       Sports
50       Yoga Mat       Sports
2   Tennis Racket       Sports
9   Tennis Racket       Sports
48  Tennis Racket       Sports
20       Yoga Mat       Sports
85       Football       Sports
19     Basketball       Sports
67     Basketball       Sports
21     Basketball       Sports
44       Football       Sports
79       Yoga Mat       Sports
78  Tennis Racket       Sports
64  Tennis Racket       Sports
30  Tennis Racket       Sports
32       Yoga Mat       Sports
46     Basketball       Sports
53       Yoga Mat       Sports

### *Alternate method using np.select*

In [110]:
df_sel=df_ecom.copy()

In [111]:
#there will create 2 variables one for conditions and other for values.
condition=[
    df_sel['Product'].isin(['Blender', 'Smartphone','Vacuum','Headphones','Laptop','Microwave','Smartwatch']),
    df_sel['Product'].isin(['Tennis Racket','Basketball','Yoga Mat', 'Football']),
    df_sel['Product'].isin(['Science','Biography','Comics','Fiction']),
    df_sel['Product'].isin(['Shoes','Jeans','Jacket','T-Shirt'])
    ]
catg=['Electronics', 'Sports', 'Books', 'Clothing']

In [112]:
#Return an array drawn from elements in choicelist, depending on conditions.
np.select(condition,catg,default='Home')

array(['Electronics', 'Electronics', 'Sports', 'Books', 'Books', 'Sports',
       'Electronics', 'Books', 'Books', 'Sports', 'Sports', 'Books',
       'Clothing', 'Books', 'Electronics', 'Books', 'Electronics',
       'Electronics', 'Books', 'Sports', 'Sports', 'Sports',
       'Electronics', 'Electronics', 'Books', 'Books', 'Clothing',
       'Electronics', 'Home', 'Books', 'Sports', 'Home', 'Sports',
       'Books', 'Clothing', 'Electronics', 'Electronics', 'Electronics',
       'Home', 'Electronics', 'Books', 'Books', 'Clothing', 'Clothing',
       'Sports', 'Electronics', 'Sports', 'Clothing', 'Sports', 'Books',
       'Sports', 'Books', 'Home', 'Sports', 'Electronics', 'Clothing',
       'Clothing', 'Clothing', 'Electronics', 'Electronics', 'Books',
       'Books', 'Electronics', 'Electronics', 'Sports', 'Clothing',
       'Clothing', 'Sports', 'Books', 'Sports', 'Clothing', 'Clothing',
       'Books', 'Home', 'Electronics', 'Electronics', 'Books',
       'Electronics', 'Sports', 'Sports', 'Electronics', 'Electronics',
       'Clothing', 'Clothing', 'Clothing', 'Sports', 'Electronics',
       'Electronics', 'Electronics', 'Home', 'Electronics', 'Books',
       'Clothing', 'Home', 'Books', 'Electronics', 'Electronics',
       'Electronics', 'Electronics'], dtype='<U11')

In [113]:
#assigning the array result to column 'Catagory'
df_sel['Category']=np.select(condition,catg,default='Home')

In [114]:
df_sel.head(15)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Revenue
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Electronics,3,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,1076.70
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.18
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Electronics,5,978.63,Bank Transfer,Processing,4893.15
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.40
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.29
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.70
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,2691.75
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.54
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.52
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.81
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.26

In [116]:
#updating the main dataframe with the changes performed
df_ecom=df_sel

# *Final datarame output after data cleaning process*

In [117]:

df_ecom.head(23)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Revenue
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Electronics,3,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,538.35,PayPal,Processing,1076.70
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.18
6,106,Customer_106,ORD-25885,2025-02-02,Blender,Electronics,5,978.63,Bank Transfer,Processing,4893.15
7,107,Customer_107,ORD-89122,2025-01-03,Biography,Books,5,587.68,PayPal,Returned,2938.40
8,108,Customer_108,ORD-64400,2025-10-23,Science,Books,1,600.29,Cash on Delivery,Processing,600.29
9,109,Customer_109,ORD-18512,2025-05-03,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.70
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,Sports,5,538.35,Cash on Delivery,Cancelled,2691.75
11,111,Customer_111,ORD-72349,2025-10-22,Comics,Books,2,865.77,Credit Card,Returned,1731.54
12,112,Customer_112,ORD-80867,2025-03-02,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.52
13,113,Customer_113,ORD-23994,2025-07-24,Fiction,Books,1,411.81,Credit Card,Processing,411.81
14,114,Customer_114,ORD-77417,2023-01-05,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.26
15,115,Customer_115,ORD-72778,2025-01-10,Fiction,Books,2,796.84,Cash on Delivery,Returned,1593.68
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,Electronics,4,538.35,Cash on Delivery,Processing,2153.40
17,117,Customer_117,ORD-72751,2025-02-12,Blender,Electronics,2,10000.00,Cash on Delivery,Processing,20000.00
18,118,Customer_118,ORD-96061,2025-05-31,Science,Books,5,247.82,PayPal,Processing,1239.10
19,119,Customer_119,ORD-76016,2024-12-19,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.76
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,Sports,5,300.00,Credit Card,Cancelled,1500.00
21,121,Customer_121,ORD-80067,2025-10-11,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.04
22,122,Customer_122,ORD-21443,2025-05-16,Microwave,Electronics,2,556.93,PayPal,Shipped,1113.86

In [118]:
#verifying the result for nulls
df_ecom.isna().sum()

ID                0
Customer_Name     0
Order_ID          0
Order_Date        0
Product           0
Category          0
Quantity          0
Price             0
Payment_Method    0
Status            0
Revenue           0
dtype: int64

In [119]:
# verfying the result for any duplicates
print(df_ecom.duplicated().sum())

0

In [121]:
df_ecom.to_csv(r"C:\Users\Admin\Ecom_DataCleaning.csv")